---
#
# Ansible managed
#
repository:
  description: Install and configure Skopeo on your system.
  homepage: https://buluma.github.io/
  topics: bootstrap, python, sudo, ansible, molecule, tox, playbook
