---
#
# Ansible managed
#

name: Auto Merge Dependency Updates

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge Dependabot Updates
        uses: buluma/gh-action-auto-merge-dependabot-updates@1.0.5
        with:
          allowed-actors: buluma, dependabot-preview[bot], dependabot[bot]
